HOSTS:
  master:
    roles:
      - master
    platform: el-6-i386
    hypervisor: vcloud
    template: redhat-6-i386
  agent:
    roles:
      - agent
    platform: solaris-11-x86_64
    hypervisor: vcloud
    template: solaris-11-x86_64
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
